###
POST http://localhost:5075/api/v1/Order
Content-Type: application/json

{
   "ProdutoUuid":"7d3af8b1-3755-4772-8f8d-72e25b1abefa",
   "UsuarioNome":"daniel",
   "UsuarioEmail":"daniel@gmail.com",
   "UsuarioTelefone":"11 2222-4444",
   "CreatedAt":"2023-07-28T18:08:55.8822567-03:00"
}

###
GET http://localhost:5075/api/v1/Order/91ebd480-962c-438f-ba2e-02f62bbb4081