apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
spec:
  selector:
    matchLabels:
      app: client

  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: dpcprofile/eshop-client
          ports:
            - containerPort: 80
          env:
            - name: "PRODUTO__URL"
              value: "http://produto-service"
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.5"

---

apiVersion: v1
kind: Service
metadata:
  name: client-service
  labels:
    app: client-service
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
  selector:
    app: client