apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
spec:
  selector:
    matchLabels:
      app: order

  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: dpcprofile/eshop-order
          ports:
            - containerPort: 80
          env:
            - name: "PRODUTO__URL"
              value: "http://produto-service"
            - name: "RABBITMQ__HOST"
              value: "rabbitmq-service"
            - name: "REDIS__HOST"
              value: redis-service
            - name: "PORTA"
              value: "80"
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.5"

---

apiVersion: v1
kind: Service
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
  selector:
    app: order