apiVersion: apps/v1
kind: Deployment
metadata:
  name: produto
spec:
  selector:
    matchLabels:
      app: produto

  template:
    metadata:
      labels:
        app: produto
    spec:
      containers:
        - name: produto
          image: dpcprofile/eshop-produto
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.5"

---

apiVersion: v1
kind: Service
metadata:
  name: produto-service
  labels:
    app: produto-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
  selector:
    app: produto